import type { NewBeer } from './schema';

/* Les 6 bières réelles du prototype (design/Brasse-Yutz Recettes.dc.html, seed() lignes 407-435). */
export const SEED: NewBeer[] = [
  {
    id: 'dark-mode', name: 'Dark Mode', styleName: 'Munich Dunkel', denomination: 'Bière brune',
    brew: 34, abv: '4', ebc: '35', ibu: '25', bottle: '75cl', accent: 'var(--cuvee-malt)', icon: 'SunMoon',
    malts: '*Orge* : Munich Light, Pale Ale, CaraMunich II, Chocolat', hops: 'Brewers Gold, Fuggle, Magnum',
    yeast: 'S-33', other: 'Eau, sucre', bottledOn: '27/09/2026', bestBefore: '09/2027', lot: 'L2609-34',
    volume: '20', og: '1,041', fg: '1,010',
    grains: 'Munich Light | 3,2 kg\nPale Ale | 0,8 kg\nCaraMunich II | 0,3 kg\nChocolat | 0,1 kg',
    hopSchedule: 'Magnum | 12 g | 60 min\nBrewers Gold | 15 g | 20 min\nFuggle | 20 g | 5 min',
    mash: 'Empâtage | 66 °C | 60 min\nMash-out | 78 °C | 10 min',
    ferment: 'S-33 | 18 °C | 12 jours\nGarde | 4 °C | 3 semaines',
    notes: 'Une brune qui se boit sans y penser. Le thème sombre, version liquide.',
    look: 'Brune acajou, reflets rubis, mousse beige fine.',
    nose: 'Pain grillé, cacao léger, une pointe de noisette.',
    mouth: 'Ronde et souple, malt toasté, corps léger pour une brune.',
    finish: 'Sèche, amertume douce qui revient sur le café.',
    serving: '8–10 °C, verre à pied.',
  },
  {
    id: 'hop-overflow', name: 'Hop Overflow', styleName: 'NEIPA',
    brew: 33, abv: '5', ebc: '11', ibu: '40', bottle: '75cl', accent: 'var(--cuvee-orange)', icon: 'Hop',
    malts: '*Orge* : Pale Ale, CaraPils, Munich, Vienna · flocons de *blé*',
    hops: 'Chinook, Citra, Nelson Sauvin, Mosaïc, Centennial',
    yeast: 'Verdant IPA', other: 'Eau, sucre', bottledOn: '07/05/2026', bestBefore: '05/2027', lot: 'L2605-33',
    volume: '20', og: '1,050', fg: '1,012',
    grains: 'Pale Ale | 4,0 kg\nFlocons de blé | 0,8 kg\nMunich | 0,4 kg\nVienna | 0,4 kg\nCaraPils | 0,3 kg',
    hopSchedule: 'Chinook | 10 g | 60 min\nCitra | 40 g | whirlpool 80 °C\nMosaïc | 40 g | whirlpool 80 °C\nNelson Sauvin | 50 g | dry hop J3\nCentennial | 50 g | dry hop J3\nCitra | 50 g | dry hop J6',
    mash: 'Empâtage | 67 °C | 60 min\nMash-out | 78 °C | 10 min',
    ferment: 'Verdant IPA | 19 °C | 10 jours\nCold crash | 2 °C | 2 jours',
    notes: 'Trouble assumée. À boire jeune, avant que les arômes ne débordent de la pile.',
    look: 'Jaune paille trouble, mousse blanche dense.',
    nose: 'Mangue, fruit de la passion, agrumes, un fond résineux.',
    mouth: 'Texture soyeuse (avoine et blé), jus de fruits tropicaux, peu d’amertume perçue.',
    finish: 'Douce, légèrement résineuse.',
    serving: '6–8 °C, à boire dans les 3 mois.',
    description: 'Le brassin 33 est né d’une envie simple : voir jusqu’où on peut pousser le houblonnage à froid sans que la bière devienne amère. Cinq houblons, deux dry hop, et une fermentation surveillée de près pour garder la texture ronde d’une NEIPA.',
  },
  {
    id: 'xmas-2025', name: 'Xmas', edition: '2025', styleName: 'Bière de Noël', denomination: 'Bière épicée',
    brew: 32, abv: '5,5', ebc: '53', ibu: '27', bottle: '33cl', accent: 'var(--cuvee-bordeaux)', icon: 'Snowflake',
    malts: '*Orge* : Pale Ale, Munich, CaraMunich, Chocolat, CaraBelge', hops: 'Mosaïc, Centennial',
    yeast: 'S-33', other: 'Eau, sucre, orange, clou de girofle, gingembre, cannelle',
    bottledOn: '15/11/2025', bestBefore: '11/2026', lot: 'L2511-32',
    volume: '20', og: '1,054', fg: '1,012',
    grains: 'Pale Ale | 3,6 kg\nMunich | 0,8 kg\nCaraMunich | 0,4 kg\nCaraBelge | 0,2 kg\nChocolat | 0,15 kg',
    hopSchedule: 'Centennial | 15 g | 60 min\nMosaïc | 20 g | 10 min',
    mash: 'Empâtage | 67 °C | 60 min\nMash-out | 78 °C | 10 min',
    ferment: 'S-33 | 19 °C | 14 jours\nÉpices | zeste, girofle, gingembre, cannelle | 5 min',
    notes: 'Les épices restent discrètes. Servez-la à 8–10 °C, pas plus froide.',
    look: 'Ambrée foncée, reflets cuivrés.',
    nose: 'Écorce d’orange, cannelle, pain d’épices.',
    mouth: 'Caramel, épices chaudes en retrait, corps moyen.',
    finish: 'Gingembre discret, légère chaleur.',
    serving: '8–10 °C.',
  },
  {
    id: 'paul', name: 'Paul', edition: 'Eph 5:18', styleName: 'Triple',
    brew: 31, abv: '8,2', ebc: '12', ibu: '24', bottle: '75cl', accent: 'var(--cuvee-houblon)', icon: 'Leaf',
    malts: '*Orge* : Pilsner, Munich, Cara Belge', hops: 'Chinook, Fuggle',
    yeast: 'Abbaye Belgian', other: 'Eau, sucre', bottledOn: '15/05/2025', bestBefore: '05/2026', lot: 'L2505-31',
    volume: '20', og: '1,070', fg: '1,008',
    grains: 'Pilsner | 5,5 kg\nMunich | 0,5 kg\nCara Belge | 0,2 kg\nSucre candi | 0,8 kg',
    hopSchedule: 'Chinook | 12 g | 60 min\nFuggle | 25 g | 15 min',
    mash: 'Empâtage | 64 °C | 75 min\nMash-out | 78 °C | 10 min',
    ferment: 'Abbaye Belgian | 20 → 24 °C | 14 jours\nGarde | 12 °C | 4 semaines',
    notes: 'Forte, à partager. Le verset sur l’étiquette n’est pas là par hasard.',
    look: 'Dorée, limpide, mousse blanche généreuse.',
    nose: 'Fruits blancs, poivre, levure belge.',
    mouth: 'Ample et sèche malgré les 8,2 %, notes de poire et d’épices.',
    finish: 'Longue, alcool bien intégré.',
    serving: '8–12 °C, verre tulipe.',
  },
  {
    id: 'pils-electrique', name: 'Pils Électrique', styleName: 'Pils', denomination: 'Bière lager',
    brew: 30, abv: '5,5', ebc: '8', ibu: '20', bottle: '75cl', accent: 'var(--cuvee-ocre)', icon: 'Zap',
    malts: '*Orge* : Pilsner, Munich, CaraPils, Vienna', hops: 'Styrian Goldings, Mosaïc',
    yeast: 'Diamond Lager', other: 'Eau, sucre', bottledOn: '24/04/2025', bestBefore: '04/2026', lot: 'L2504-30',
    volume: '20', og: '1,052', fg: '1,010',
    grains: 'Pilsner | 4,4 kg\nVienna | 0,4 kg\nMunich | 0,2 kg\nCaraPils | 0,2 kg',
    hopSchedule: 'Styrian Goldings | 25 g | 60 min\nMosaïc | 20 g | 10 min\nStyrian Goldings | 20 g | 0 min',
    mash: 'Protéines | 52 °C | 10 min\nEmpâtage | 65 °C | 60 min\nMash-out | 78 °C | 10 min',
    ferment: 'Diamond Lager | 11 °C | 14 jours\nGarde | 2 °C | 5 semaines',
    notes: 'Une lager nette, qui demande surtout de la patience au froid.',
    look: 'Or pâle, très limpide.',
    nose: 'Céréales, fleurs, touche herbacée.',
    mouth: 'Nette et vive, malt pils, houblon floral.',
    finish: 'Sèche, amertume franche et courte.',
    serving: '4–6 °C.',
  },
  {
    id: 'citra-xtra', name: 'Citra Xtra', styleName: 'American Pale Ale', denomination: 'Bière APA',
    brew: 26, abv: '5', ebc: '11', ibu: '38', bottle: '75cl', accent: 'var(--cuvee-houblon)', icon: 'Citrus',
    malts: '*Orge* : Pale Ale, Pilsen · flocons de *froment*, malt de *blé*', hops: 'Citra',
    yeast: 'S-04', other: 'Eau, sucre', bottledOn: '18/07/2024', bestBefore: '07/2025', lot: 'L2407-26',
    volume: '20', og: '1,049', fg: '1,011',
    grains: 'Pale Ale | 3,6 kg\nPilsen | 0,6 kg\nMalt de blé | 0,4 kg\nFlocons de froment | 0,3 kg',
    hopSchedule: 'Citra | 10 g | 60 min\nCitra | 30 g | 10 min\nCitra | 40 g | whirlpool\nCitra | 60 g | dry hop J4',
    mash: 'Empâtage | 66 °C | 60 min\nMash-out | 78 °C | 10 min',
    ferment: 'S-04 | 19 °C | 10 jours',
    notes: 'Un seul houblon, en quantité. Le nom dit tout.',
    look: 'Blonde dorée, légèrement voilée.',
    nose: 'Pamplemousse, citron vert, litchi.',
    mouth: 'Agrumes, base maltée légère.',
    finish: 'Amertume nette, agrumes persistants.',
    serving: '6–8 °C.',
  },
];
